# Generated by Django 2.2.16 on 2022-09-07 17:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220907_2041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_cannot_rate_themselves',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='user_cannot_follow_himself'),
        ),
    ]
